import { Movie } from '../movie';

export const MOVIES: Movie[] = [
  { id: 1, title: 'Go lang', text: '1', thumbnail: 'gopher.png' },
  { id: 2, title: 'Go lang', text: '2', thumbnail: 'gopher.png' },
  { id: 3, title: 'Go lang', text: '3', thumbnail: 'gopher.png' },
  { id: 4, title: 'Go lang', text: '4', thumbnail: 'gopher.png' },
  { id: 5, title: 'Go lang', text: '5', thumbnail: 'gopher.png' },
  { id: 6, title: 'Go lang', text: '6', thumbnail: 'gopher.png' },
  { id: 7, title: 'Go lang', text: '7', thumbnail: 'gopher.png' },
  { id: 8, title: 'Go lang', text: '8', thumbnail: 'gopher.png' },
  { id: 9, title: 'Go lang', text: '9', thumbnail: 'gopher.png' },
  { id: 10, title: 'Go lang', text: '10', thumbnail: 'gopher.png' },
  { id: 11, title: 'Go lang', text: '11', thumbnail: 'gopher.png' },
  { id: 12, title: 'Go lang', text: '12', thumbnail: 'gopher.png' },
  { id: 13, title: 'Go lang', text: '13', thumbnail: 'gopher.png' },
  { id: 14, title: 'Go lang', text: '14', thumbnail: 'gopher.png' },
  { id: 15, title: 'Go lang', text: '15', thumbnail: 'gopher.png' },
  { id: 16, title: 'Go lang', text: '16', thumbnail: 'gopher.png' },
  { id: 17, title: 'Go lang', text: '17', thumbnail: 'gopher.png' },
  { id: 18, title: 'Go lang', text: '18', thumbnail: 'gopher.png' },
  { id: 19, title: 'Go lang', text: '19', thumbnail: 'gopher.png' },
  { id: 20, title: 'Go lang', text: '20', thumbnail: 'gopher.png' },
  { id: 21, title: 'Go lang', text: '21', thumbnail: 'gopher.png' },
  { id: 22, title: 'Go lang', text: '22', thumbnail: 'gopher.png' },
  { id: 23, title: 'Go lang', text: '23', thumbnail: 'gopher.png' },
  { id: 24, title: 'Go lang', text: '24', thumbnail: 'gopher.png' },
  { id: 25, title: 'Go lang', text: '25', thumbnail: 'gopher.png' },
  { id: 26, title: 'Go lang', text: '26', thumbnail: 'gopher.png' },
  { id: 27, title: 'Go lang', text: '27', thumbnail: 'gopher.png' },
  { id: 28, title: 'Go lang', text: '28', thumbnail: 'gopher.png' },
  { id: 29, title: 'Go lang', text: '29', thumbnail: 'gopher.png' },
  { id: 30, title: 'Go lang', text: '30', thumbnail: 'gopher.png' },
  { id: 31, title: 'Go lang', text: '31', thumbnail: 'gopher.png' },
  { id: 32, title: 'Go lang', text: '32', thumbnail: 'gopher.png' },
  { id: 33, title: 'Go lang', text: '33', thumbnail: 'gopher.png' },
];
