import { Movie } from '../movie';

export const MOVIES: Movie[] = [
  { id: 1, title: 'Go lang', thumbnail: 'assets/images/mock.png' },
  { id: 2, title: 'python', thumbnail: 'assets/images/mock.png' },
  { id: 3, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 4, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 5, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 6, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 7, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 8, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 9, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 10, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 11, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 12, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 13, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 14, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 15, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 16, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 17, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 18, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 19, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 20, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 21, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 22, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 23, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 24, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 25, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 26, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 27, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 28, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 29, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 30, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 31, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 32, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 33, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 34, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 35, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 36, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 37, title: 'Gopher', thumbnail: 'assets/images/mock.png' },
  { id: 38, title: 'Gopher', thumbnail: 'assets/images/mock.png' }
];
